services:
  - type: worker
    name: discord-faq-bot
    runtime: node
    plan: starter
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PREFIX
        value: "!"
      - key: OVERLAYS_CHANNEL_URL
        sync: false
      - key: TOPAZ_CHANNEL_URL
        sync: false
      - key: MRBIT_USER_ID
        sync: false
      - key: DISCORD_TOKEN
        sync: false
